### ISSUE TITLE
Some images not high quality? 

### ISSUE THREAD

**Issue by mpagels** [lmachens/trophy-hunter-landing#1]
Hey Leon, awesome work with the optimization of your landing page.
I've visited it with my smartphone (galaxy s10/firefox for Android) and I asked myself if the images (attached screenshot) are a bit to much unsharp?
![Screenshot_20210710-143929_Firefox](https://user-images.githubusercontent.com/54703643/125163454-86045000-e18d-11eb-8a83-6c841cb8d831.jpg)

**Comment by lmachens** [comment]
Thx Martin!
I updated the assets with higher quality and set width and height for better optimization.
On my mobile device, there was no issue. Can you tell me if it is better now?

**Comment by mpagels** [comment]
Yes much better on my side. ![](https://i.imgur.com/Qj09nQm.jpg)
